### ISSUE TITLE
InvalidArgumentError when running the first step as I tried to run read_csv.py

### ISSUE THREAD

**Issue by Jaxonwht** [WolfNiu/polite-dialogue-generation#1]
This error occurs in tf 1.3, 1.10 and 1.12. They all happen in the first step written on the README.md.
```bash
Traceback (most recent call last):
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Quoted field has to end with quote followed by delim or end
	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_FLOAT], field_delim=",", na_value="", select_cols=[], use_quote_delim=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2:1, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_13)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/basic/read_csv.py", line 66, in <module>
    (sent, score) = sess.run([request, score_normalized])
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Quoted field has to end with quote followed by delim or end
	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_FLOAT], field_delim=",", na_value="", select_cols=[], use_quote_delim=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2:1, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_13)]]

Caused by op 'DecodeCSV', defined at:
  File "src/basic/read_csv.py", line 54, in <module>
    csv_row, record_defaults=record_defaults)
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/parsing_ops.py", line 1232, in decode_csv
    select_cols=select_cols,
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_parsing_ops.py", line 76, in decode_csv
    na_value=na_value, select_cols=select_cols, name=name)
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Quoted field has to end with quote followed by delim or end
	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_FLOAT], field_delim=",", na_value="", select_cols=[], use_quote_delim=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2:1, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_13)]]
```

**Comment by shahidmohana** [comment]
I am facing the same error repeatedly

**Comment by joseph12346** [comment]
I have same problem

**Comment by dmgcsilva** [comment]
Did any of you ever figure this out?

**Comment by suxilalala** [comment]
> This error occurs in tf 1.3, 1.10 and 1.12. They all happen in the first step written on the README.md.
> 
> ```shell
> Traceback (most recent call last):
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
>     return fn(*args)
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Quoted field has to end with quote followed by delim or end
> 	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_FLOAT], field_delim=",", na_value="", select_cols=[], use_quote_delim=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2:1, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_13)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "src/basic/read_csv.py", line 66, in <module>
>     (sent, score) = sess.run([request, score_normalized])
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
>     run_metadata_ptr)
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
>     run_metadata)
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Quoted field has to end with quote followed by delim or end
> 	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_FLOAT], field_delim=",", na_value="", select_cols=[], use_quote_delim=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2:1, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_13)]]
> 
> Caused by op 'DecodeCSV', defined at:
>   File "src/basic/read_csv.py", line 54, in <module>
>     csv_row, record_defaults=record_defaults)
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/parsing_ops.py", line 1232, in decode_csv
>     select_cols=select_cols,
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_parsing_ops.py", line 76, in decode_csv
>     na_value=na_value, select_cols=select_cols, name=name)
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
>     return func(*args, **kwargs)
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
>     op_def=op_def)
>   File "/dscrhome/hw186/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> InvalidArgumentError (see above for traceback): Quoted field has to end with quote followed by delim or end
> 	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_FLOAT], field_delim=",", na_value="", select_cols=[], use_quote_delim=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2:1, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_13)]]
> ```

Have you solved the problem？
